### ISSUE TITLE
Support different database engines

### ISSUE THREAD

**Issue by ged15** [deis/controller#1113]
First of all, thank you for the great work on Deis. You people rock! :)
I do not know how good Django's DB abstraction layer is, but is there a reason the DB engine is hardcoded to PostgreSQL (https://github.com/deis/controller/blob/0d830247b3635c097bd8605dddc745fa957ece35/rootfs/api/settings/production.py#L325)?
Having the ability to use MySQL as the DB engine, would make it very easy to host an off-cluster DB in GCloud.

**Comment by helgi** [comment]
There hasn't ever been a strong reason why Postgres only in the past but at this point we have started using Postgres only features and it would be a bit painful to back them out and use more generic solutions.

If you want to help us then that'd be appreciated. It does add a certain burden - We have to test everything in Postgres + other DB tech, and whoever owns that needs to write (and maintain) a MySQL DB chart as well so people that are not using off-cluster hosted DBs (like RDS / GCloud) can pick MySQL, and we can run it in our e2e tests.

**Comment by bacongobbler** [comment]
IIRC beforehand there was some differences in how different databases handled atomic updates. Some prototyping would be required to accomplish this.

**Comment by mboersma** [comment]
I don't *think* we're using transactions in any way that would preclude Oracle or MySQL as the backend database. But the database migrations are vendor-specific and might have to be reimplemented, and there are likely other places where PostgreSQL is assumed.

Adding new DB vendors would also complicate the testing matrix quite a bit, and I'm not sure we want to take that on...

**Comment by krancour** [comment]
I don't work on the controller much, but if I can weigh in on this, I'm really torn on whether this is something we should do or not. I'm just going to toss out a few different thoughts (from multiple perspectives) that popped into my head in case these considerations resonate with anyone else.

1. I'm no Django expert, but does it not offer Rails-like engine-agnostic migrations? Are we just not using them? I know in Rails, with many apps, there comes a point where you have to stop using those engine-agnostic migrations and lock into a particular db engine if you want to access engine-specific features. Are we really dependent on Postgres-specific features? If so, what are they?

1. From a certain perspective, the fact that Workflow is currently locked into PostgreSQL doesn't seem like such a huge deal. We live in a day in age when IaaS and SaaS should have made _any_ sort of DB a commodity. Provisioning a PG database for Workflow shouldn't be out of the question for most users. Even if this means your cluster and your DB live in different clouds, that should be ok. (Latency between the controller and the DB only affect the performance of a few platform operations and don't impact application performance at all.) _That being said..._

1. GKE seems to be a hugely popular option for hosting Workflow clusters and it seems "natural" that GKE users would want to leverage other GCP services. GCP offers MySQL, but not Postgres. _But having said that..._

1. I do not (personally) recommend GKE/GCP as a viable option for _production_ clusters anyway (mainly because-- unrelated-- networking options are a bit constraining). Again, this is largely personal preference, but _for me_, that takes some weight off of point no. 3 above and weights point no. 2 more heavily.

**Comment by helgi** [comment]
@krancour yeah it's Rails like in the sense it should be agnostic - What @mboersma and co are referring to (correct me if I am wrong) is prior it wasn't as solid around atomic transactions and other similar things when it came to MySQL (or generally other DBs?)

Especially now, not out of the question at all but there is some heavy lifting to be done (for example we use ArrayField, and potentially JSONField, PG only atm), test matrix does get larger and so on.

I do agree with point 3 having some truth to it - Thought GCP did Postgres

**Comment by krancour** [comment]
@helgi they offer MySQL as a service (similar to Amazon's RDS), but if you want Postgres, you get compute capacity from GCP and do it yourself ala EC2.

**Comment by rimusz** [comment]
For GCP/GKE Workflow setup you can use hosted PD from compose.io, which allows to hots your PG in GCP.

**Comment by bacongobbler** [comment]
This is something we are not going to tackle due to the added complexity to the testing matrix, additional recommended docs as well as the dragons that may be laying in the cave. postgres has been good to us.
