### ISSUE TITLE
Authentification with LDAP

### ISSUE THREAD

**Issue by rvadim** [deis/controller#1140]
Hi,
thank you for your work.
Do you planning to turn back functionality of LDAP auth?
We work with ~90 users and planning to migrate from deis 1.0. Ask all users to register one more time, not very good idea for us.

Thank you.

**Comment by bacongobbler** [comment]
We pulled it out because we have no way to test LDAP ourselves, but if you feel like making a PR to restore it and maintain LDAP support we'd happily accept a PR. :)

**Comment by Kooper** [comment]
LDAP support was removed in [`2883c0c`](https://github.com/deis/controller/pull/208/commits/2883c0cb87c61493b7136f6ad15e5b72ab831c96) because of the couple of issues.

First it is django-auth-ldap==1.2.5 which is incompatible with Django 1.9 This is clear and would be easy to check with updated module.

Second is a need of 'better identity and federation story' which stumbled me. Can you or @helgi please elaborate this a bit? The patch looks like mostly configuration change, removing just one of the authentication backends and it's dependencies. It gives no clue to federation or identities model problems and their relation to LDAP auth. Searching through issues I was also unable to find how LDAP authentication influenced model in previous or current versions.

So summarizing, what kind of pull request is required to bring LDAP integration back? Is it sufficient to just revert the patch with up2date version of django-auth-ldap after checking, or there are any core problems with users model which should be addressed before enabling one more authentication backend?

**Comment by kmala** [comment]
fixed in #1156
