### ISSUE TITLE
Validate certificate on certs:add

### ISSUE THREAD

**Issue by ineu** [deis/controller#1155]
In the current implementation when you add an invalid certificate, deis-controller adds it and supplies it to the deis-router. Nginx tries to reload and fails with the following error:
```
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/opt/router/ssl/foo.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
```
This has the following consequences:
1. Nginx can no longer reload. If you add a new application, it will always give 404. New nginx config will be generated, but nginx can never load it because of certificate issue. At least existing applications will run.
2. Should the router pod die, Kube will try to restart it and will always fail because nginx cannot start with incorrect certificate. This makes all applications inaccessible. Furthermore, this makes `deis` subdomain inaccessible as well, which makes it impossible to remove incorrect certificate via `deis certs:remove`.

Thus the controller should validate an uploaded certificate when the `deis certs:add` command is performed and give user a feedback if the certificate is incorrect.

**Comment by bacongobbler** [comment]
To add context to this issue, we attempt to [load the X509 certificate](https://github.com/deis/controller/blob/092f9105db692bb7a4daf8224249d8ec1732b7b0/rootfs/api/models/certificate.py#L67-L71) when it is being added to the API server, so that is being validated. This error indicates that the private key supplied with the X509 certificate is invalid, and [we do not provide any validation logic](https://github.com/deis/controller/blob/092f9105db692bb7a4daf8224249d8ec1732b7b0/rootfs/api/models/certificate.py#L81-L82) in the controller for the private key. We can [probably do the same](http://www.pyopenssl.org/en/stable/api/crypto.html#OpenSSL.crypto.load_privatekey).
