### ISSUE TITLE
[question]: is possible to migrate from V1?

### ISSUE THREAD

**Issue by aledbf** [deis/controller#294]
Running `deis/workflow` using a v1 postgres db I see this error:
```
system information:
Django Version: 1.9.1
Python 3.5.1
Operations to perform:
  Apply all migrations: api, auth, contenttypes, guardian, admin, authtoken, sessions, sites
Running migrations:
  Rendering model states... DONE
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: relation "auth_group" already exists
```

This is (in part) related to the changes in migrations. Old `deis-controller` uses `south_migrationhistory` table and `deis/workflow` `django_migrations`.

**Comment by aledbf** [comment]
Using the next sequence of commands is possible to use the content (not the db itself)

dump old database:
```
pg_dump \
  -h <hostname> \
  -U deis \
  -d deis \
  -f deis-dump.sql \
  -t api_app \
  -t api_build \
  -t api_certificate \
  -t api_config \
  -t api_container \
  -t api_domain \
  -t api_key \
  -t api_push \
  -t api_release \
  -t auth_user \
  -t auth_user_groups \
  -t auth_user_user_permissions \
  -a -b -O -W
```

remove content from new db:
```
delete from authtoken_token
delete from auth_user
```

import content:
```
psql deis < deis-dump.sql
```

**Comment by bacongobbler** [comment]
The south migration scripts were not ported over from v1 to v2, so it won't be as easy to port over the data. I think we still need to figure out how we're gonna do a data migration once we come out with a stable release for v2, but it'll likely be something similar to how you're describing.

cc @helgi

**Comment by helgi** [comment]
@aledbf you hit the nail on the head as to why this is somewhat hard to pull off.

We are working up some docs on how we are going to handle migrations and such but like @bacongobbler pointed out the migration path is not a walk in the park due to Django updates, and also we have been doing incompatible data model changes in v2 (not too many so far).

We have considered data exporters / importers via dumps like you did @aledbf but right now we have not proved it out. It may have to be a combo of a dump like you have there and some "massaging" of the data.

Lets leave this ticket open to aggregate ideas / what needs to happen

**Comment by aledbf** [comment]
@helgi just in case that sequence is working with `deis/workflow` master

**Comment by helgi** [comment]
Yeah, that's great to know. Hadn't tried that yet :) Thanks!

I'm working on some certificate changes that logs more information to DB based on the certificate which may require some extra work for future imports like that tho the initial loading script on `boot` may take care of that

**Comment by Joshua-Anderson** [comment]
I think it's been determined that the database cannot be ported from Deis V1 to workflow. Can this be closed?

**Comment by bacongobbler** [comment]
Indeed
