### ISSUE TITLE
[Proposal]: Add secret to add common env variables

### ISSUE THREAD

**Issue by aledbf** [deis/controller#383]
The idea is to add environment variables like the new relic license, platform wide health check url (to avoid setting the url in each application), etc. (this variables can be overwritten by the config in the application)
The goal is to avoid the fork of the project just to customize the env section of the RC template

**Comment by helgi** [comment]
@aledbf Would these be env vars that are applied to all RCs in all apps or are you looking for some amount of control over that as well?

**Comment by aledbf** [comment]
> applied to all RCs in all apps

I think this is the correct use case. 
If I need more control then `config:set -a <app>` is the right tool for that.

**Comment by helgi** [comment]
This seems like an unlikely case but what if I have an app that does *not* want one of the global values?

The options are
* set the value to empty (your code will have to deal with that in the app)
* somehow have the ability to unset a global var on a local level

In most cases I'd imagine people are more wanting to have a different new relic license so if they just set the same env var on their app then that would just overwrite, since we'd do a merge that preferred local app configs

But then the question becomes, do we ever want to have an env var defined global that applications can't overwrite?

I think i'm going for edge cases here but I'm interested in some thoughts on those

**Comment by bacongobbler** [comment]
closing in favour of #1219.
