### ISSUE TITLE
bug(workflow): _healthcheck func def port should be the equal to PORT env

### ISSUE THREAD

**Issue by aledbf** [deis/controller#403]
```
env variable PORT=5000
_healthcheck port=8080
```

**Comment by helgi** [comment]
Isn't this the same as https://github.com/deis/workflow/issues/373 ? @smothiki can you look at this

**Comment by aledbf** [comment]
@helgi yes and no :) the default value for port in the `_healthcheck` function is 8080 and it should be 5000

**Comment by helgi** [comment]
5000 is only for slugs, for docker images and such it is 8080, the way @smothiki made it work so that as it pulls the target port from the k8s services for the app (https://github.com/deis/workflow/blob/master/rootfs/scheduler/__init__.py#L705-L706) but then fallsback on the default if needed

slugs use this template https://github.com/deis/workflow/blob/master/rootfs/scheduler/__init__.py#L127-L128 and https://github.com/deis/workflow/blob/master/rootfs/scheduler/__init__.py#L127-L128

Tho the more I look at the logic the more wonky I think this is ...

@smothiki What's stopping us from just exposing all apps as 5000 or 8080, regardless of app type?

**Comment by helgi** [comment]
Haven't heard anything more about this. Things seem to work as intended despite what is set as default
