### ISSUE TITLE
Scale returns some containers in initialized state

### ISSUE THREAD

**Issue by gabrtv** [deis/controller#459]
Seeing weird container states after a scale operation.  I'd expect everything to be `up` before we return.

```
$ deis scale web=10
Scaling processes... but first, coffee!
done in 124s
=== zircon-addendum Processes
--- web:
zircon-addendum-v3-web-1pchs up (v3)
zircon-addendum-v3-web-23c64 up (v3)
zircon-addendum-v3-web-duj6q up (v3)
zircon-addendum-v3-web-j00na up (v3)
zircon-addendum-v3-web-sjljt initialized (v3)
zircon-addendum-v3-web-vus0o up (v3)
zircon-addendum-v3-web-wmp6k initialized (v3)
zircon-addendum-v3-web-xx3qd up (v3)
zircon-addendum-v3-web-ze4yo initialized (v3)
zircon-addendum-v3-web-vkrt8 up (v3)
```

**Comment by gabrtv** [comment]
I should note that this occurred on a "cold" cluster, where the `deis/slugrunner` image was not yet present on all the worker nodes -- hence the 124 seconds.  Subsequent scale operations aren't reproducing this:

```
$ deis scale web=10
Scaling processes... but first, coffee!
done in 11s
=== zircon-addendum Processes
--- web:
zircon-addendum-v3-web-3n2op up (v3)
zircon-addendum-v3-web-813fp up (v3)
zircon-addendum-v3-web-aa6cc up (v3)
zircon-addendum-v3-web-jln0b up (v3)
zircon-addendum-v3-web-r97xq up (v3)
zircon-addendum-v3-web-0efcj up (v3)
zircon-addendum-v3-web-ewkbw up (v3)
zircon-addendum-v3-web-n8hic up (v3)
zircon-addendum-v3-web-vinew up (v3)
zircon-addendum-v3-web-z6ktl up (v3)
```

**Comment by helgi** [comment]
Wonder if you hit any of our timeouts. Tho one out of many of them are 120s, so technically your scale up could take 10+ minutes if every single timeout loop is touched.

Problem here is very likely like you said the slugrunner image is being copied in for the first time and is *huge*, this should however keep a pod in a Pending state. Right now the scale operations may not be super friendly to that first download to be totally honest.  Should we? How long should we let an image download from a k8s perspective before our scaling cope bails out?

When the image is downloaded from a kubernetes perspective everything looks quite good because there are no healthchecks by default from outside - It thinks the image is there and everything is ready to start booiting up. Basically k8s sees it as started pods so any downloads of the slug itself and untar'ing is going to be extra "wait" time.

To me this all spells out some of the weaknesses of the slug builder / slug runner concepts and how we are somewhat breaking the k8s model with it.
