### ISSUE TITLE
Cannot connect to restored database

### ISSUE THREAD

**Issue by krancour** [deis/controller#536]
This might actually be a database issue... I'm not sure.

It seems, however, that controller is never able to connect to a database that has been restored from backups.  With a fresh db, there is no problem.

**Comment by bacongobbler** [comment]
@krancour how have you been testing this? just `kubectl --namespace=deis delete pod <database pod>`?

**Comment by krancour** [comment]
Nope... afaict, I have all components successfully using s3 for object storage now... so I've been going through scenarios where I helm uninstall the entire platform and then re-install.

**Comment by bacongobbler** [comment]
Hmm. Perhaps you're hitting https://github.com/deis/postgres/issues/56. I just ran `helm uninstall && help install` without any drama, however I know that issue is still occurring today. I found my controller on a CrashLoopBackOff, but after deleting the pod the controller came up and is now able to communicate with the database.

That being said, there was no data in the database...

```
><> deis apps
Error: 
401 Unauthorized
detail: Invalid token.
```

Let's route all stuff over to deis/postgres#56 and try to figure out why wal-e is being a pain.
