### ISSUE TITLE
Health Checks and how they are displayed to the end user

### ISSUE THREAD

**Issue by helgi** [deis/controller#549]
Ever since https://github.com/deis/controller/commit/81a5c37fb4d3b35a022fe8eac4bbd43113f75ae7#diff-ffb566d124a367aa8d7bd107a49d8313 health checks have not been enabled unless `HEALTHCHECK_URL` is set but even then we are not auto backfilling other other default values back into the database.

This means if I set a healh check url and then list out the configs for my app I will not be able to see all the other default values, so as a developer I have to know what defaults Deis Workflow set. That's not very useful

One option is to start auto saving the default values into the DB if the developer is not using them. That way a `config:list` will show all the required values, as I would expect to see from a Web UI. The problem with that approach is that if we ever decide to change the defaults that means anything we have auto saved to the database is "dirty" and a migration for that is not the simplest.

The other option is to return all the defaults via `config:list` or similar that are not set via `config:set` but not save them to the database, only if the URL is set minimum.

Thoughts?

/cc @slack

**Comment by slack** [comment]
I like saving defaults to the database because it:
* is clear, in things like `config:list` that there is some configuration or knobs that are coming into play
* protects later platform releases from breaking working applications because we changed a default

The last point being the most important, IMO.

There are a few circumstances where that behavior isn't ideal, but it seems the costs outweighs the protection for later changes.
