### ISSUE TITLE
bug: Incorrect type in service

### ISSUE THREAD

**Issue by aledbf** [deis/controller#571]
In an app with multiple types (web and cron), the created service used cron as `type`.
(if the app defines multiple type, always uses the last one as `type` in the service)

**Comment by helgi** [comment]
Yeah hmmm that's not great. Right now `deploy` updates the `service` on the fly so if you have multiple types I can see how that affects it.

Reason for doing the `service` upfront (with default information) is so we can add `domain` and other information ahead of time. I'll have to see if I can just make it prefer routable services. The `port` is going to be the same issue here. The last `process type` will win out, right now.

Now I am wondering what we should do if we have `cron` and `worker` but no `routable` apps then what should the service prefer?

**Comment by helgi** [comment]
https://github.com/deis/controller/pull/573 will fix part of this problem but mostly solves for #572 - This makes the scheduler only apply the type once instead of trying to constantly update it

Talked it through with @aledbf and here is what I think we want to do:

Feed types in the deploy so that routable services are always deployed first, which makes it “win”. Basically sort them according to if they are routable or not
