### ISSUE TITLE
question: why services are updated after a pull or git push?

### ISSUE THREAD

**Issue by aledbf** [deis/controller#572]
This is related to #571.
I can fix the service/s manually but I found out that after each release the service is updated with the incorrect mapping

**Comment by helgi** [comment]
I explained it in #571 but to reiterate:

Reason for doing the service upfront (with default information) is so we can add domain and other information ahead of time. Without creating the service ahead of time then we need to go back to adding application `domain` (the name of your app) to the service since that's what the router (right now) uses to pick up what domains to route to the service

At creation time there is no type defined so the problem you are talking about here is actually the same as #571. Each proc type you have gets deployed and the last one wins out currently

It is impossible to create a service without a `port` for example so that needs a default value, intended to be updated later.

**Comment by helgi** [comment]
Fixed by https://github.com/deis/controller/pull/573
