### ISSUE TITLE
port https://github.com/deis/deis/pull/5005 to v2

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#597]
port https://github.com/deis/deis/pull/5005 to v2

**Comment by helgi** [comment]
Awesome, also in Python 3.4+ there are more `unittest` capabilities around logging which we may be able to plug into

**Comment by helgi** [comment]
I was playing around with the `assertLogs` thing and well given how we interact with the API majority of the time then doing the `assertLogs` didn't work since it was out of the context :|

But in your case (i just checked again) you are interacting with the objects directly so it should be doable without using `called_with` and similar
