### ISSUE TITLE
Proposal ref(controller): do not wait 120s for termination

### ISSUE THREAD

**Issue by aledbf** [deis/controller#621]
The default `terminationGracePeriodSeconds` is 30 seconds.This means that after this time the pod is killed. During a deploy the controller waits for the removal of the pod. 
This makes no sense because some pods can stay in the state of termination (for several reasons) and the controller spent up to 120s per pod in an operation out of the scope of deis.

**Comment by helgi** [comment]
Part of it is due to how we do 1 in (pod) of new RC and 1 out of old RC during deploys.

We could be more aware of the terminationGracePeriodSeconds and just wait for that period and give up on waiting on the pod after that point. We'd have to amend our pod list operation to hide those pods so `ps` and friends do not get confused.

**Comment by aledbf** [comment]
@helgi please check the issues with the [`Terminating` state in pods](https://github.com/kubernetes/kubernetes/search?q=terminating&type=Issues )
