### ISSUE TITLE
If pods are in crashloop you cant scale down

### ISSUE THREAD

**Issue by jchauncey** [deis/controller#756]
```
╰─± kgpo --namespace=foo
NAME               READY     STATUS             RESTARTS   AGE
foo-v2-web-ouxev   0/1       Error              0          3s
foo-v2-web-rcy89   0/1       CrashLoopBackOff   1          11s
foo-v2-web-tdl9g   1/1       Running            0          11h
╭─jonathanchauncey at ENG000637 in ~/projects/deis/example-go on master✔ using ‹2.2.2›
╰─± deis scale web=1
Scaling processes... but first, coffee!
done in 0s
=== foo Processes
--- web:
foo-v2-web-ouxev error (v2)
foo-v2-web-rcy89 error (v2)
foo-v2-web-tdl9g up (v2)
```

**Comment by jchauncey** [comment]
This was the error in the pods -

```
╰─± kl foo-v2-web-newaa --namespace=foo
2016/05/27 15:45:52 Error downloading home/foo:git-3e6834d7/push/slug.tgz (s3aws: Path not found: home/foo:git-3e6834d7/push/slug.tgz)
```

**Comment by helgi** [comment]
It's the nature of how scale works (currently) - When determining the status of the world we first:

1. Gather all pods we consider in a ready state
2. Compare that to the desired number
3. If the desired vs current is not accurate we go and scale up / down

In your case you said scale=1 and there was already only 1 ready pod (because the others were in various other states).

We could start accounting for other states and try to make smarter choices but we can't take any actions on pods that are in the "pre-ready" state IMO and only act on pods that are in some sort of an error / failing state... Tho maybe not? Maybe you should be able to do scale=10, ctrl + c and then scale=1 and have it blow the pods that are starting up away
