### ISSUE TITLE
HEALTHCHECK_URL url encoding

### ISSUE THREAD

**Issue by sstarcher** [deis/controller#774]
When supplying a HEALTHCHECK_URL to deis config:set that contains a ```?``` it gets encoded when past into the Kubernetes liveness probe.

Steps:
* deis config:set HEALTHCHECK_URL=/servlet/status?test_datasources=0
* deis config:get HEALTHCHECK_URL - shows the value as not encoded
* kubectl describe pod --namespace=app APP - shows the value as encoded and the health check never passes
```http-get http://:8080/servlet/status%3Ftest_datasources=0 delay=120s timeout=120s period=10s #success=1 #failure=10```

**Comment by helgi** [comment]
When I run the `config:set` command and then do `kubectl get po --namespace=app` and look at the health check there then the URL is not encoded, but I can see in `describe` that it is.

What we call `URL` is actually `path` in Kubernetes health checks, I did some spelunking and it looks like Kubernetes does not support query parameters

If you look at this https://github.com/kubernetes/kubernetes/blob/59b7b1c550945c23790a9f1baa79ff32b9c527a6/pkg/kubelet/prober/prober.go#L160 and then at the following method `formatURL` https://github.com/kubernetes/kubernetes/blob/59b7b1c550945c23790a9f1baa79ff32b9c527a6/pkg/kubelet/prober/prober.go#L210-L216

https://golang.org/pkg/net/url/#URL Since `formatURL` only specifies `Path` and not `RawPath` - The format auto-encodes

Nothing much we can do. I'll have to update our documentation and potentially rename HEALTCHECK_URL to HEALTHCHECK_PATH for clarity tho that is a bit of a breakage at this point

**Comment by sstarcher** [comment]
Sounds good thanks for tracking that down.

**Comment by therc** [comment]
@helgi: I submitted a fix to formatURL that was merged a week after this issue:

https://github.com/kubernetes/kubernetes/pull/25064

So things should be better with 1.3.
