### ISSUE TITLE
Apps deployed from GCR with `deis pull`, get targetPort 5000 instead of 80

### ISSUE THREAD

**Issue by rimusz** [deis/controller#799]
The problem comes when 'deis registry:set username=_json_key password="$(cat google_cloud_cred.json | jq -c .)"' is used.
SVC and RC get targetPort set as 5000 instead of 80.

**Comment by helgi** [comment]
Setting `PORT` is a requirement when you use private registry as we are not longer downloading the image to the Controller to be able to divine the port as private images are only pulled into Kubernetes. We default to `5000` currently.

For the version you are using this is working as intended.

https://github.com/deis/controller/pull/791 fixes that to be an explicit requirement instead of defaulting and updates the documentation.

**Comment by rimusz** [comment]
that is not documented so peeps can be cut by that issue

**Comment by helgi** [comment]
Correct and if you look at the PR it links to a doc fix as well

**Comment by rimusz** [comment]
but the doc's PR is not merged yet :)
