### ISSUE TITLE
Apps with healthchecks from 2.0 are broken in 2.1

### ISSUE THREAD

**Issue by sstarcher** [deis/controller#856]
@bacongobbler 
I have so far produced this twice with 2 separate applications.  The only fix so far for me was to destroy the application.

Deployment
```
Creating build... ...Error: 
400 Bad Request
detail: public-v49-cmd (app::deploy): ('failed to create ReplicationController "public-v49-cmd" in Namespace "public": 422 status code 422\n{\'metadata\': {}, \'code\': 422, \'reason\': \'Invalid\', \'kind\': \'Status\', \'status\': \'Failure\', \'message\': \'ReplicationController "public-v49-cmd" is invalid: spec.template.spec.containers[0].livenessProbe.httpGet.port: Invalid value: "80": must be an IANA_SVC_NAME (at most 15 characters, matching regex [a-z0-9]([a-z0-9-]*[a-z0-9])*, it must contain at least one letter [a-z], and hyphens cannot be adjacent to other hyphens): e.g. "http"\', \'details\': {\'name\': \'public-v49-cmd\', \'causes\': [{\'message\': \'Invalid value: "80": must be an IANA_SVC_NAME (at most 15 characters, matching regex [a-z0-9]([a-z0-9-]*[a-z0-9])*, it must contain at least one letter [a-z], and hyphens cannot be adjacent to other hyphens): e.g. "http"\', \'reason\': \'FieldValueInvalid\', \'field\': \'spec.template.spec.containers[0].livenessProbe.httpGet.port\'}], \'kind\': \'ReplicationController\'}, \'apiVersion\': \'v1\'}', 'public-v49-cmd', 'public')
```

List
```
deis healthchecks:list -a public                                                                                    
=== public Healthchecks

--- Liveness
Initial Delay (seconds): 10
Timeout (seconds): 50
Period (seconds): 10
Success Threshold: 1
Failure Threshold: 3
Exec Probe: N/A
HTTP GET Probe: Path="/" Port=0 HTTPHeaders=[]
TCP Socket Probe: N/A

--- Readiness
No readiness probe configured.
```

Unset and set fail
```
deis healthchecks:unset liveness -a public                                                                            
Removing healthchecks... Error: This action could not be completed due to a conflict.
```

**Comment by bacongobbler** [comment]
Why would the port need to be an IANA_SERVICE_NAME? Gonna ping @helgi on this one for clues.

**Comment by sstarcher** [comment]
@bacongobbler @helgi fixed something prior that was related to I think ports being a string back prior to 2.0

If i look at my pods they are defined as
```
    Liveness:		http-get http://:80/ delay=10s timeout=50s period=10s #success=1 #failure=3
    Readiness:		http-get http://:80/ delay=10s timeout=50s period=10s #success=1 #failure=3
```

so it's odd that deis healthchecks:list says the Port is 0

**Comment by helgi** [comment]
Yeah ports have to be strings, otherwise kubernetes will think it is a named port

**Comment by helgi** [comment]
Ehh it had to be an integer, not a string

**Comment by sstarcher** [comment]
I'm guessing with the healthcheck changes @helgi port change may of gotten broken

**Comment by sstarcher** [comment]
But I wonder why it's affecting my situation and not others

**Comment by bacongobbler** [comment]
> so it's odd that deis healthchecks:list says the Port is 0

To explain this, the old legacy healthchecks do not require a port. It is "magically" obtained by inspecting the image internally before being deployed. The downside of this is when an application exposes multiple ports, the controller cannot determine *which* one to healthcheck, and the user cannot change this behaviour. It is now required for the user to add a port to any httpGet healthchecks to avoid this "magic logic". Being explicit in this case is better.

Since it is unavailable in the controller response, the CLI must parse the JSON object and return *something* so it displays zero.

In any case, #857 should resolve this regression.

**Comment by sstarcher** [comment]
@bacongobbler my app actually has the PORT environment variable set

**Comment by bacongobbler** [comment]
#857 converts it to a proper int. It's old logic from `release.get_port` where in cases when the user has set PORT, it is returned as a string instead of an int. We missed the casting logic so that situation was missed out. If you didn't set PORT and the port number was inferred from the image, then this would not have occurred. Essentially this only happens in one specific edge case:

 - you have HEALTHCHECK_* environment variables set for healthchecks
 - you have manually set PORT

Those two conditions must be met in order to trigger this bug. As a temporary workaround, you can remove your HEALTHCHECK_* environment variables and move to `deis healthchecks` instead.

**Comment by sstarcher** [comment]
deis config:unset HEALTHCHECK_URL

```
Removing config... Error: Unknown Error (400): map[detail:public-v11-cmd (app::deploy): ('failed to failed to update Secret "public-v11-env" in Namespace "public": 400 Bad Request\n{\'status\': \'Failure\', \'code\': 400, \'message\': \'Secret in version "v1" cannot be handled as a Secret: [pos 264]: json: error decoding base64 binary \\\'/\\\': illegal base64 data at input byte 0\', \'reason\': \'BadRequest\', \'apiVersion\': \'v1\', \'metadata\': {}, \'kind\': \'Status\'}', 'public-v11-env', 'public')]
```
