### ISSUE TITLE
controller assumes the application is ready based soley on the readiness probe

### ISSUE THREAD

**Issue by sstarcher** [deis/controller#874]
If the application has a liveness probe, but not a readiness probe the application will immediately become ready.

```
--- Liveness
Initial Delay (seconds): 50
Timeout (seconds): 50
Period (seconds): 10
Success Threshold: 1
Failure Threshold: 3
Exec Probe: N/A
HTTP GET Probe: Path="/servlet/status" Port=8080 HTTPHeaders=[]
TCP Socket Probe: N/A

--- Readiness
No readiness probe configured.
```

I'm not 100% certain rather is is an oddity in k8s or deis, but with a liveness probe and an initial delay of 50 seconds I would expect the application to not be live for a minimum of 50 seconds.  Instead as soon as the pods are in a Running state the old application is terminated.

After creating a readiness probe with an initial delay of 50 seconds it works as expected.

**Comment by bacongobbler** [comment]
This will be fixed by #854.

**Comment by sstarcher** [comment]
@bacongobbler I don't believe this would address #854 
After reading the kubernetes documentation I believe Deis is functioning as expected except for the migration path from HEALTHCHECK_*.  When migrating from HEALTHCHECK_* a liveness probe is created when most users would expect a readiness probe or both.

**Comment by bacongobbler** [comment]
Originally it created both a liveness and a readiness which is something I missed. However it makes more sense to just create a liveness since if both probes have the same values and the liveness fails then the container goes down.

For the sake of fixing up the zero downtime deploys, yes we should check the initial delay on both liveness and readiness probes configured for the app. PRs welcome as I won't have enough time to fix this for 2.2 unless someone else wants to tackle this in the next few days. Code freeze is Friday.

**Comment by sstarcher** [comment]
@bacongobbler no hurry just bringing it to your attention.  Creating a readiness probe solves the issue.

**Comment by helgi** [comment]
Give #884 a go
