### ISSUE TITLE
open registration is an insecure default

### ISSUE THREAD

**Issue by tmc** [deis/controller#950]
compromising a cluster via the default serviceaccount would be trivial.

**Comment by helgi** [comment]
Are you referring to `deis register` or specifically the create ServiceAccount in Kubernetes? If it is the latter then deis/charts is the place to report it (=

**Comment by jchauncey** [comment]
My proposal is as follows:

 1. Create a user in the database using a migration script (should have a check to make sure no other user exists so this does not interfere with existing installations)
 1. Upon start up of the deis platform we figure out how to inform the operator about said username/password
 1. When the operator logs into that user for the first time we prompt them to change the password of said account.

I am also not convinced we should allow public registration. Or at least that should not be the default. We should take the stance that the default installation of deis delivers a production quality installation with as much security in place as we can afford.

**Comment by rimusz** [comment]
What about setting e.g. user/password in `generate_params.toml` or prompt for the password on `helmc generate -x manifests workflow-v2.....`?

**Comment by bacongobbler** [comment]
In my opinion, it is up to the administrator to lock down their cluster. We provide a REGISTRATION_MODE flag to lock down administration or only allow admins to create users, but it is open season by default for ease of use. This is well documented in both the production recommendations and all over the docs. Can you please explain why we should shift over, and is there an agreement from others that this should be the default? In my opinion it's a blocker for the "turnkey" solution to get Workflow up and running, not to mention a massive complication in the docs and in existing video recordings/tutorials.

**Comment by jchauncey** [comment]
Fact is even for non production environments people are potentially deploying sensitive apps into staging clusters that may be exposed to the world. This means the controller is exposed. The default stance of the platform should be to be as secure as possible out of the box because honestly that would be what most people would choose regardless. 

People do not want something open and less secure if they have an option for soemthing else. So why not give it to them?

**Comment by bacongobbler** [comment]
We do. Register your first user, swap REGISTRATION_MODE to admin_only and reboot the controller. I'm not sure what's the difference between those steps as described in the documentation and what's proposed here, which is a massive breaking change.

One compromise could be to change admin_only mode to only come in effect after an administrator has been initially registered, then make it the default. I'm just opposed to the idea of "secure by default" and block all registration by default, which in my mind reads "why can't I use my cluster, I can't register???"

**Comment by bacongobbler** [comment]
I'm closing this as we are not going to be changing the default registration mode, however if you'd like to make an enhancement to the admin_only registration mode, PRs are more than welcome.

**Comment by tmc** [comment]
I expect more respect for security from EngineYard than this.

**Comment by bacongobbler** [comment]
We can talk about changing the default registration mode for v3, but not for v2 as I said, it's an API-level breaking change. We have documentation providing best practice" around good defaults for production that includes thorough documentation around switching to admin_only registration mode. We take security seriously. Is there something else you'd prefer?

**Comment by jchauncey** [comment]
I think having an easy way to disable registration without having to use
kubectl would be a good first step

**Comment by bacongobbler** [comment]
> I think having an easy way to disable registration without having to use
kubectl would be a good first step

You can [change it in the chart](https://github.com/deis/workflow/blob/db774f58cdca79d636c99a675bb0c8c54d95bad1/charts/workflow/values.yaml#L105-L109). No need to use kubectl to change the registration mode. Just use `helm install deis/workflow --namespace deis --set controller.registration_mode=admin_only`.

I'm going to re-open this to gauge interest from the community if it's worth changing the default registration mode to "admin only" by default, breaking backwards compatibility.

My main concern is two-fold as I've mentioned earlier:

1. We break backwards compatibility. Technically we should release a v3.0.0 if we're going to do this change.
2. Due to 1), users have come to expect this behaviour of open registration by default, but we make is [abundantly clear](https://deis.com/docs/workflow/managing-workflow/production-deployments/#change-registration-mode) in the documentation that one should change it when running Workflow in prod.

If we do decide to go ahead with this, we need to make it VERY clear in the release notes about this change, or we need to release a v3.0.0 with this one change to be good semver citizens. Personally, I'm in favour of the latter, but then we need to explain to users that v3 is no different than v2, which I bet will confuse users because they'd come to expect a MASSIVE shift due to the v1 -> v2 migration.

**Comment by bacongobbler** [comment]
So according to many others around the topic of updating default config values, it appears it is completely OK to create a minor release while changing a default value. With that said, I'm OK with changing the default to admin_only.

Couple of action items:

 - change [the value in the chart](https://github.com/deis/workflow/blob/db774f58cdca79d636c99a675bb0c8c54d95bad1/charts/workflow/values.yaml#L109)
 - update the production documentation
 - update any other relevant documentation about registering users, probably [Users and Registration](https://deis.com/docs/workflow/users/registration/) for starters

**Comment by mboersma** [comment]
> Our Semver contract only applies to API or CLI-level breaking changes, not default configuration in the chart. With that said, I'm OK with changing the default to `admin_only`.

I agree with this reasoning, and this "insecure by default" behavior should be changed.

**Comment by tmc** [comment]
Arguably having open registration at all is an insecure default -- the admin user could be provided or generated in the initial helm install.

**Comment by bacongobbler** [comment]
There may be use cases where open registration is an OK practice, such as on a self-hosted cluster in an offline private network, where only trusted users are allowed on the network. We should allow all use cases, insecure or not. What mode they run in is completely up to the administrator, and we should allow such cases.

> the admin user could be provided or generated in the initial helm install.

The current system is fine. PRs are welcome to do that if you need it.

**Comment by mboersma** [comment]
> the admin user could be provided or generated in the initial helm install

That would help even more by removing the initial registration window. We would love to review a PR that implements that as an option.

I agree with @bacongobbler that there are valid use cases for `enabled`. Also for backward-compatibility we can't remove it regardless. For now, making `admin_only` the default registration mode seems like a worthwhile step.
