### ISSUE TITLE
admin should be able to do lower kubernetes config on apps

### ISSUE THREAD

**Issue by jsimnz** [deis/controller#984]
Admin users deploying apps should be able to add lower level application configs for kubernetes. For example settings hostPaths for mounting, or custom restartPolicies.

I know #858 talked about hostPaths, and it was determined that it would result in security issues if allowed. However the deis admin user should freely be able to add configs that normal users can't, even if it could potentially vulnerable. Much in the same way the root on unix machines can pretty much do whatever.

**Comment by jsimnz** [comment]
If this is a permissible feature, I'll happily hack away at it.

**Comment by Joshua-Anderson** [comment]
I belive @helgi has some concerns about this being difficult to do safely and adding complexity to the controller. If you have some time you might want to chat in the deis community slack channel about what exactly this feature would look like.

**Comment by bacongobbler** [comment]
I think we've though about this and shut it down. There's some discussion ongoing in https://github.com/deis/controller/issues/240#issuecomment-239926693 that you might be interested in talking about. The first step would be to write out a doc proposal first before implementing so we can all agree on an idea.

**Comment by helgi** [comment]
@jsimnz We haven't heard back from you in a while. I'm going to close this ticket due to inactivity but if you were wanting to work on this could you open up a more detailed proposal at https://github.com/deis/workflow on how this would work, how an admin would interact with this and the considerations if people wanted to remove parts of the core template(s) which would affect Deis functionalities
